#!/usr/bin/env bash
# Generated by Hard Eng. Downloads the release pinned in hard-eng.gates.json, then prepares this checkout.
# Usage: bootstrap.sh <claude|codex|copilot>   at session start
#        bootstrap.sh download                 download and verify only
set -euo pipefail
mode=${1:?usage: bootstrap.sh <claude|codex|copilot|download>}
root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)
if ! command -v python3 >/dev/null 2>&1; then
  echo "hard-eng bootstrap: python3 3.12 or newer is required" >&2
  exit 1
fi
export PYTHONDONTWRITEBYTECODE=1
exec python3 - "$root" "$mode" <<'PY'
import hashlib
import json
import os
import shutil
import stat
import subprocess
import sys
import tarfile
import tempfile
import urllib.request
from pathlib import Path

root, mode = Path(sys.argv[1]), sys.argv[2]
MAX_ARCHIVE = 64 * 1024 * 1024
MAX_MANIFEST = 1024 * 1024
AGENTS = ("claude", "codex", "copilot")


def log(message):
    print(f"hard-eng bootstrap: {message}", file=sys.stderr, flush=True)


def fail(message):
    log(message)
    raise SystemExit(1)


if mode not in (*AGENTS, "download"):
    fail(f"unknown mode: {mode}")
try:
    policy = json.loads((root / "hard-eng.gates.json").read_text(encoding="utf-8"))["hard_eng"]
    pin = policy["pin"]
    tag, archive_sha, manifest_sha = pin["tag"], pin["archive_sha256"], pin["manifest_sha256"]
except (OSError, ValueError, KeyError, TypeError) as error:
    fail(f"hard-eng.gates.json has no usable Hard Eng pin: {error}")
release_repository = policy.get("release_repository", "sgaabdu4/hard-eng")
base = os.environ.get("HARD_ENG_RELEASE_BASE_URL") or f"https://github.com/{release_repository}/releases/download"
local = root / ".agents" / "hard-eng"
target = local / "releases" / tag


def sha256(path):
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def fetch(name, destination, expected, limit):
    url = f"{base}/{tag}/{name}"
    try:
        with urllib.request.urlopen(url, timeout=120) as response, destination.open("wb") as handle:
            copied = 0
            while block := response.read(1024 * 1024):
                copied += len(block)
                if copied > limit:
                    fail(f"{name} is larger than the {limit} byte limit")
                handle.write(block)
    except OSError as error:
        fail(f"could not download {url}: {error}")
    if sha256(destination) != expected:
        fail(f"{name} does not match the digest pinned in hard-eng.gates.json")


def tree_digest(base_dir):
    digest = hashlib.sha256()
    for path in sorted(base_dir.rglob("*"), key=lambda value: value.relative_to(base_dir).as_posix()):
        relative = path.relative_to(base_dir).as_posix()
        metadata = path.lstat()
        kind = b"directory" if stat.S_ISDIR(metadata.st_mode) else b"file"
        digest.update(kind + b"\0" + relative.encode() + b"\0")
        digest.update(f"{stat.S_IMODE(metadata.st_mode):04o}".encode() + b"\0")
        if kind == b"file":
            digest.update(str(metadata.st_size).encode() + b"\0")
            with path.open("rb") as handle:
                for block in iter(lambda: handle.read(1024 * 1024), b""):
                    digest.update(block)
    return digest.hexdigest()


def write_json(path, value):
    temporary = path.with_name(f".{path.name}.{os.getpid()}.tmp")
    with temporary.open("w", encoding="utf-8") as handle:
        handle.write(json.dumps(value, sort_keys=True, separators=(",", ":")) + "\n")
    os.chmod(temporary, 0o600)
    os.replace(temporary, path)


def cached():
    try:
        state = json.loads((local / "last-check.json").read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return False
    if not isinstance(state, dict) or state.get("pin") != pin or not (local / "current").is_symlink():
        return False
    return (target / ".hard-eng-release.json").is_file() and tree_digest(target) == state.get("payload_digest")


def extract(archive, stage):
    prefix = f"hard-eng-{tag}/"
    with tarfile.open(archive, "r:gz") as bundle:
        members = []
        for member in bundle.getmembers():
            if member.name == prefix.rstrip("/"):
                continue
            if not member.name.startswith(prefix) or not (member.isdir() or member.isfile()):
                fail(f"unexpected release archive entry: {member.name}")
            member.name = member.name[len(prefix) :]
            members.append(member)
        bundle.extractall(stage, members=members, filter="data")


def download():
    with tempfile.TemporaryDirectory(prefix="hard-eng-bootstrap-") as temporary:
        archive = Path(temporary) / f"hard-eng-{tag}.tar.gz"
        manifest_path = Path(temporary) / f"hard-eng-{tag}.manifest.json"
        fetch(archive.name, archive, archive_sha, MAX_ARCHIVE)
        fetch(manifest_path.name, manifest_path, manifest_sha, MAX_MANIFEST)
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        if not isinstance(manifest, dict) or manifest.get("version") != tag:
            fail("the release manifest does not describe the pinned tag")
        for directory in (local.parent, local, local / "releases"):
            directory.mkdir(mode=0o700, exist_ok=True)
        stage = Path(tempfile.mkdtemp(prefix=".installing-", dir=local / "releases"))
        try:
            extract(archive, stage)
            write_json(stage / ".hard-eng-release.json", manifest)
            if target.exists():
                shutil.rmtree(target)
            os.replace(stage, target)
        finally:
            shutil.rmtree(stage, ignore_errors=True)
    link = local / "current"
    temporary_link = local / f".current.{os.getpid()}"
    temporary_link.symlink_to(Path("releases") / tag)
    os.replace(temporary_link, link)
    write_json(
        local / "last-check.json",
        {
            "active_version": tag,
            "channel": policy.get("channel"),
            "last_result": "pinned-verified",
            "marker_digest": None,
            "minimum_version": policy.get("minimum_version"),
            "newest_allowed_version": tag,
            "payload_digest": tree_digest(target),
            "pin": pin,
            "release_repository": release_repository,
            "schema_version": 1,
            "source_commit": manifest.get("source_commit"),
        },
    )
    log(f"downloaded and verified Hard Eng {tag}")


def session(agent):
    first_claude_session = agent == "claude" and not (root / "CLAUDE.local.md").exists()
    environment = {name: value for name, value in os.environ.items() if not name.startswith("GIT_")}
    result = subprocess.run(
        [sys.executable, str(target / "bin" / "hard-eng"), "prepare", "--repo", str(root), "--agent", agent],
        check=False,
        capture_output=True,
        text=True,
        env=environment,
        stdin=subprocess.DEVNULL,
        timeout=600,
    )
    if result.returncode != 0:
        fail(result.stderr.strip() or result.stdout.strip() or "hard-eng prepare failed")
    if first_claude_session:
        rules = (target / "AGENTS.md").read_text(encoding="utf-8")
        output = {"hookEventName": "SessionStart", "additionalContext": rules, "reloadSkills": True}
        print(json.dumps({"hookSpecificOutput": output}))


if not cached():
    download()
if mode != "download":
    session(mode)
PY
