#!/usr/bin/env bash
# Generated by Hard Eng. Runs the pinned Hard Eng guard, or denies tool calls until the release is downloaded.
set -u
agent=${1:-}
event=${2:-}
root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)
cache=$root/.agents/hard-eng
if [ -f "$cache/global-guard" ] && grep -qx -- "$agent" "$cache/global-guard"; then
  exit 0
fi
guard=$cache/current/scripts/hooks/agent-hook.sh
if [ -f "$guard" ]; then
  exec bash "$guard" "$@"
fi
case $event in
  posttooluse|stop) exit 0 ;;
esac
reason="Hard Eng is not downloaded for this repository yet, so this tool call was denied. Run: bash .hard-eng/bootstrap.sh $agent"
if [ "$agent" = copilot ]; then
  printf '{"permissionDecision":"deny","permissionDecisionReason":"%s"}' "$reason"
else
  printf '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":"%s"}}' "$reason"
fi
