name: example
description: Demonstrates how to use the vault_storage package.
publish_to: "none"

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  vault_storage:
    path: ../
  file_picker: ^12.0.0
  path_provider: ^2.1.6

flutter:
  uses-material-design: true
