name: example
description: Demonstrates how to use the vault_storage package.
publish_to: "none"

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  vault_storage:
    path: ../
  file_picker: ^13.1.0
  path_provider: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_secure_storage: ^11.2.0
  hive_ce_flutter: ^2.3.4

flutter:
  uses-material-design: true
